# Generated by Django 3.0.5 on 2020-06-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtree', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edit',
            options={'managed': False},
        ),
    ]
