# Generated by Django 3.0.5 on 2020-06-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cno', models.IntegerField(blank=True, null=True)),
                ('cname', models.CharField(blank=True, max_length=20, null=True)),
                ('des', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TreeEntity',
            fields=[
                ('id', models.IntegerField()),
                ('entity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pno', models.IntegerField()),
                ('pname', models.CharField(max_length=20)),
                ('p_x', models.FloatField()),
                ('p_y', models.FloatField()),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('dbh', models.FloatField(blank=True, null=True)),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('plant_company', models.CharField(blank=True, max_length=50, null=True)),
                ('plant_date', models.DateField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.CharField(blank=True, max_length=50, null=True)),
                ('feature', models.CharField(blank=True, max_length=50, null=True)),
                ('usage', models.CharField(blank=True, max_length=50, null=True)),
                ('health', models.CharField(blank=True, max_length=50, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=4, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('image_id', models.IntegerField(blank=True, null=True)),
                ('recorder_id', models.IntegerField()),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('checker_id', models.IntegerField()),
                ('check_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tree_entity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TreeSpecies',
            fields=[
                ('pno', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('alias', models.CharField(blank=True, max_length=30, null=True)),
                ('foreign_name', models.CharField(blank=True, max_length=30, null=True)),
                ('latin', models.CharField(blank=True, max_length=30, null=True)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=30, null=True)),
                ('generic', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('origin', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('trait', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tree_species',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TreeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField()),
                ('pno', models.IntegerField()),
                ('pname', models.CharField(max_length=20)),
                ('p_x', models.FloatField()),
                ('p_y', models.FloatField()),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('dbh', models.FloatField(blank=True, null=True)),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('plant_company', models.CharField(blank=True, max_length=50, null=True)),
                ('plant_date', models.DateField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.CharField(blank=True, max_length=50, null=True)),
                ('feature', models.CharField(blank=True, max_length=50, null=True)),
                ('usage', models.CharField(blank=True, max_length=50, null=True)),
                ('health', models.CharField(blank=True, max_length=50, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=4, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('image_id', models.IntegerField(blank=True, null=True)),
                ('recorder_id', models.IntegerField()),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('way', models.IntegerField(blank=True, null=True)),
                ('checked', models.IntegerField()),
            ],
            options={
                'db_table': 'tree_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('uname', models.CharField(blank=True, max_length=30, null=True)),
                ('passport', models.CharField(blank=True, max_length=20, null=True)),
                ('upriority', models.IntegerField(blank=True, null=True)),
                ('ucompany', models.CharField(blank=True, max_length=30, null=True)),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
